// PTSans font with Cyrillic support - Base64 encoded
// This is a subset of PTSans-Regular optimized for Russian text

export const addCyrillicFont = async (doc: any) => {
  // Load PTSans font from Google Fonts CDN
  const fontUrl = 'https://cdn.jsdelivr.net/npm/@fontsource/pt-sans@4.5.0/files/pt-sans-cyrillic-400-normal.woff';
  
  try {
    const response = await fetch(fontUrl);
    const arrayBuffer = await response.arrayBuffer();
    const base64 = btoa(
      new Uint8Array(arrayBuffer).reduce((data, byte) => data + String.fromCharCode(byte), '')
    );
    
    doc.addFileToVFS('PTSans-Regular.ttf', base64);
    doc.addFont('PTSans-Regular.ttf', 'PTSans', 'normal');
    doc.setFont('PTSans');
    return true;
  } catch (error) {
    console.error('Failed to load Cyrillic font:', error);
    return false;
  }
};

// Alternative: Embed a minimal Cyrillic font directly
// This is Roboto subset with Cyrillic characters
export const ROBOTO_CYRILLIC_BASE64 = `AAEAAAASAQAABAAgR0RFRgBKAAgAAAHsAAAAKEdQT1MFijLgAAACFAAAAJxHU1VCkw6GFQAAAZQAAABMT1MvMl7hXi8AAAHgAAAAYGNtYXAbpqJ7AAACsAAAAJJnYXNwAAAAEAAAAagAAAAIZ2x5ZhvUwZ0AAANEAAAWiGhlYWQdX9L7AAAApAAAADZoaGVhB90DxgAAANwAAAAkaG10eFaQCp8AAAEAAAAAhGxvY2E1MjMUAAADRAAAAERtYXhwADIAwgAAASwAAAAgbmFtZU67dYwAABnMAAABtHBvc3T/bQBkAAABqAAAAAQAAQAAAAEAACjhp99fDzz1AAsD6AAAAADatJLQAAAAANq0ktAAAP84A+gDGAAAAAgAAgAAAAAAAAABAAADGP84AEQD6AAAAAAATgABAAAAAAAAAAAAAAAAAAAAIQABAAAAIQByAAUAAAAAAAIAAAABAAEAAABAAC4AAAAAAAQD6AGQAAUACAKKArwAAACMAooCvAAAAeAAMQECAAACAAUDAAAAAAAAAAAAARAAAAAAAAAAAAAAAFBmRWQAQAAg+wQDGP84AEQDGAB8AAAAAQAAAAAAAALMADIAAAAAAlgAAAMgAAAD6ABIA+gAUAPoAMgD6ABQA+gAFAPoAHQD6AAoA+gBDAPoAQ4D6AECA+gAOAPoABYD6AAWA+gAKAPoAFAD6AB0A+gBIgPoAFoD6ABQA+gAdAPoABQD6ABwA+gAZAPoAFoD6ABIA+gAMgAAABQAAAADAAAAHAABAAAAAABMAAADAAAAAAABAAAAAAAAAAAAAAYAAAAAAAACAAAAAwAAABQAAAAEAAAAsAABAAAAAABGAAMAAQAAABwABAAwAAAACAAIAAIAAAAAAH/+wf/aAP//AAAAAAAAAAAAAQAAAAAAAAD/AAAAAAAAAAEAAAAAAAD+AAAAAAD/AAAAAAAAAAAAAAAAAAD9AAAA/wAAAAAAAAD+AAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAABkAGQAZABkALQBAgFQAZAB3gIsAnoCygMYA2oDvAQKBFgEqATyBUAFjgXcBi4GdAbEBxAHYge0CAQIUgigCO4JQAmQCd4KLAp6AAAAAwAyAAABLALMAAMABwALADdANAoBAQQBTAAEAgECBAFtBQEDAwBdAAAAC0sAAgIBXQABAQwBTAAACAcGBQQDAAMAAxEGBxUrEyERISURMxEBIRElMgEU/uwDlCj9FAEs/tRkAUr+tgFg/qACQP3AAAD//wAAASwCzAAiABAAAABDR7T/SAAAAAIASP/4At4DHAAXACgAM0AwJh8eFxQTBgEAAUwAAwMCXQACAhJLAAEBAF0AAAATAEwZGAAYKBknABcAFxQkBAcWKyQGIyImNTQ2MzIWFRQGBwYVFBYzMjY1NCYnBiMiJjU0NjMyFhUUBgcGFQL+Y05RZmZRTmNDNjVJOThJLx0lJzA4ODAlJy8hGmJoaGJQampQQWkeHTM2Rkw+Rw8hOC0sODgtKjkXFAAAAwBQ//gC/AMcABQAJAA0AEdARDIrKiMgHwYBAAFMAAADAQMAAW0ABQACAwUCZwADAwRdBgEEBBJLAAEBBF0ABQQTBUwWFQAALy0VNCQzABQAFBMmBwcXKyQGIyImJyY1NDYzMhYVFAYHBhUUFgEmJjU0NjMyFhUUBgcGFRQWJRYVFAYjIiY1NDY3NjU0JgMCY05LYBgXZmZRTmM0NjUt/o4dLzglJzAxIRocSQEGF2ZRUGZYOC03STBoa0hDTlBqakBBah4cMjdGARIfOS0rODgtKjgXFjM2RiBDTlBqaFFFaB4dMzZGAAIAyP/8AwoDHAAYACoARkBDKCEgGRYVBgEAAUwAAwMCXQACAhJLBAEAAA5LAAEBBV4ABQUTBUwaGQAAGSoZKSQjIh8eHRwAGAAYEREREyQGBxorIQYjIiY1NDYzMhYVFAYHDgIVFBYzMjY3ATY1NCYjIgYVFBYXFjMyNjUDCktOUWZmUU5jQDQ7OyE1OSs/FP5eMS45NTZJLR4lOUYwaGhiUGprQD5jISBDPSk0RTA0AXgfMzNGTDxFEBM+SwAAAQBU//gCvAMcACIAKUAmIBsUDgMCAAFMAAICAV0AAQESSwAAAANdAAMDEwNMJCQUIgQHGCskBiMiJjU0NjMyFhUUBgcGFRQWMzI2NTQmJyY1NDYzMhYVFAYCfWNOUWZmUU5jPDQ1STk4SS4bGGZGRl9iOmhoYlBqa0BBaB4dMzZGTD5HEA4rQUpaV0xeAAEAFP/4AqQDHAAoAEJAPyYfHhcUEwYCAAFMAAADAQMAAW0AAgADAAIDZwAEBAVdAAUFEksAAQEGXQAGBhMGTAAAKCcjIiAeHBQkIQcHGCskBiMiJjU0NjMyFhUUBgcGFRQWMzI2NzY1NCYjIgYVFBYXFjMyNjU0JgKkYU9RZmZPUWM/NjVJOy8/FDAwOThHLx0mJzRJM2hoaGJPamtBQGgeHTM3Ri40HzQ0RkxAQw8TJy06PAD//wB0//gDcgMcACYAAwAAAAcAGACSAAD//wAo//gDJgMcACYABQAAAAcAGABGAAD//wBD//gDQQMcACYACgAAAAcAGABhAAD//wBD//gDQQMcACYACgAAAAcAGwBhAAD//wBC//gDRAMcACYACQAAAAcAGwBkAAD//wA4//gDNgMcACYACAAAAAcAGwBWAAAAAQAW//gCqgMcACsAO0A4KR4dGBcFAAEBTAABAAIAAQJtAAQEBV0ABQUSSwADAwBeBgEAABMATAAAACspKCYjHhwUJCIHBxgrJAYjIiY1NDYzMhYVFAYHBhUUFjMyNjU0JicmNTQ2MzIWFRQGBwYVFBYzMjYCoWNOUWZmUU5jPDQ0STk5SS0bFGZOUWJCMzJJODk6aGhiUGprQEFoHh0zNkZMPkcPDitBSl1QSV8fHzU2RjZCAAABABb/+AKqAxwAKwA7QDgpHh0YFwUAAQFMAAEAAgABAmUABAQFXQAFBRJLAAMDAF4GAQAAEwBMAAAAKykoJiMeHBQkIgcHGCskBiMiJjU0NjMyFhUUBgcGFRQWMzI2NTQmJyY1NDYzMhYVFAYHBhUUFjMyNgKhY05RZmZRTmM8NDRJOTlJLRsUZk5RYkIzMkk4OTpoaGJQamtAQWgeHTM2Rkw+Rw8OK0FKXVBJXx8fNTZGNkIAAAABACD/+AL6A14AGQAnQCQVDgkCAQABTAACAgFdAAEBFEsAAAADXQADAxMDTBUTFCQEBxgrJAYjIiYnJjU0NjMyFhUUBgcGFRQWMzI2NTQBmmNOSWIcHWZmUU5jOjU1STk5Rk5nSENOUGprQEFoHh4zNkY+RwD//wBQ//gC/AMcACIABAAAAEMCNAAsAAAAAAACAFD/+AL8AxwAFAAzAEtASDAoKCIUExIFAwIAAUwAAAMBAwABbQAHAAIDBwJnBgEDAwRdCAEEBBJLAAUFBF0ABQQTBUwWFQAAMC4WMxUyKyoAFAAUEyYJBxcrJAYjIiYnJjU0NjMyFhUUBgcGFRQWJRYVFAYjIiYnJjU0NjMyFhUUBgcGFRQWMzI3Njc2NQMCZk5LXxgYZmZRTmI1NjUt/lAXZU5KYRgXZWZRTmM0NjVJOSQgJREsQGpqSENOUGprQD9rHhwzN0YsIEROUGdIRE1QamlBQGkeHTI3RjQkHRAiAAIAdP/4A3IDHAAYADAAUkBPLiYmIBgXFgcDAQABTAAAAwIDAAJtAAcEAQEDCAEEBwRnBQEDAwJdBgECAhJLAAgIAl0ACAITCEwaGQAALCopIyIfHhkwGi8AGAAYFCQJBxcrJAYjIiYnJjU0NjMyFhUUBgcOAhUUFjMyNgE2NTQmIyIGFRQWFxYzMjU0JicmNTQ2A3JjTktgGBdmZlFOYzQ2OzshNTorPxT+NjEuOTU2SS0dJjJJLRsYZjBoaUhDTlBqa0BBah4gQz0pNEQxNAGJHzMzRkw8RRATMkQ1Dw4rQUoAAAEAIv/4AqADHgAnAD9APCUeFxAJAgABTAMBAgAAAQIAZQAEBAVdAAUFFEsAAQEGXgcBBgYTBkwAAAAnJiMiIB0bFBMREA8kCAcXKyQGIyInJicmJjU0NjMyFhUUBgcGFRQWMzI3Njc2NTQmIyIGFRQWFxYCT2NOKyAoGjBeZlFOYzw0NUk5JB8mESwuOTU2SS0dMGhfHhoQRkZQamtAQWgeHTM2RjQkHRQiMkZMPEUQEwAAAQBa//gC0AMcACEAMEAtHxgRCgMBAAFMAAICAV0AAQESSwAAAANdBAEDAxMDTAAAACEgHRsVExQkBQcXKyQGIyImJyY1NDYzMhYVFAYHBhUUFjMyNjc2NTQmIyIGFRQCdWROSWEZGWZmT1FjPDQ1STkuQRUvMDk4SepoZ0hETVBqa0BAaB8eMzZGMC8fMzNGTDsAAAABAFT/+AK8AxwAJQA+QDsjHBUSCwQBAAFMAAEAAgABAmUABAQFXQAFBRJLAAMDAF4GAQAAEwBMAAAAJSQhIB4bGRQTERAPJAcHFyskBiMiJjU0NjMyFhUUBgcGFRQWMzI3Njc2NTQmIyIGFRQWFxYzMjYCdGNOUWZmUU5jQDQ1STkkHyURLC45NTZJLRoiJzlGOmhoYlBqa0BAaR4dMzZGNCQdFSIyRkw8RQ8TJy0AAQBw//gCrgMcAC4AP0A8LCUeEQoDAAIBTAACAAEAAgFtAAQEBV0ABQUSSwADAwBeBgEAABMATAAAAC4tKikoJRQTIyIhJAcHFyskBiMiJjU0NjMyFhUUBgcGFRQWMzI2NTQmJyY1NDYzMhYVFAYjIiYnJjU0JiMiBgKldE1UaGhVTWNDNjZJOTlJLRsUZk5VY2NQTWYYFjQ3Ojl0aGhiUmprQEFpHh0zNkZMPkcPDitBSl1QSl5qSENONzpCO////wBk//gCogMcACYADAAAAEMBlgBIAAAAAAABAFr/+ALQA0AAHQBDQEAbFBMSCwQBAAFMAAEAAgABAmUFAQMDAF4GAQAAFEsABAQAXgYBAAAHXQAHBxMHTAAAAB0cGRgWExEQDyQIBxcrJAYjIiYnJjU0NjMyFhUUBgcGFRQWMzI3Njc2NTQmAnVmTklhGBlmZk9RYzw0NUk5MB4nFCsuLWhoRkNNUGprQD9oHx4zNkYzHxwUI0H//wAS//gCogK6ACIADQAAAAcASQAAAAAA//8AMv/4ArYC4gAiAA4AAABDAbYASAAAAAAAAQAAAAABkALMABMAHEAZEAkCAQABTAEBAAASSwABARMBTBUTEgIHFysFNDY1NCYjIgYVFBYVFAYHBjY1NAEoWUQzMT9VUUsaE3w+ah8tPURAOSgdY18qEyNMNwAAAAABAAAAAAGQAswAEwAcQBkQCQIBAAFMAQEAABJLAAEBEwFMFRMSAgcXKwU0NjU0JiMiBhUUFhUUBgcGNjU0AShZRDMxP1VRTBQQ83teHzE9REA1KB1hYC0TIEgxAAAAABQAAAADAAAAHAAEAEQAAAAQABAAAwAAAAAgAC8APgBIAFoAbAB7AKcArQC0AMMAzQDeAO4A/gEVAWgBfP/kAAAAAAAOAAAAAAAAABYAAAAOAAAAAAAAABwAAAAYAAAAAAAAABwAAAAeAAAAAAAAACAAAAAkAAAAAAAAACQAAAAqAAAAAAAAACYAAAAuAAAAAAAAACgAAAAyAAAAAAAAACwAAAA2AAAAAAAAADAAAAA6AAAAAAAAADQAAAAeAAAAAAAAADgAAAAgAAAAAAAAADwAAAAiAAAAAAAAAEAAAAAoAAAAAAAAAEQAAAAsAAAAAAAAAEgAAAA0AAAAAAAAAEwAAAA+AAAAAAAAAFAAAABKAAAAAAAAAFQAAABWAAAAAAAAAFgAAABiAAAAAAAAAFwAAABuAAAAAAAAAGAAAAB6AAAAAAAAAGQA`;

// Function to add embedded Cyrillic font to jsPDF
export const addEmbeddedCyrillicFont = (doc: any) => {
  try {
    doc.addFileToVFS('Roboto-Regular.ttf', ROBOTO_CYRILLIC_BASE64);
    doc.addFont('Roboto-Regular.ttf', 'Roboto', 'normal');
    doc.setFont('Roboto');
    return true;
  } catch (error) {
    console.error('Failed to add embedded font:', error);
    return false;
  }
};

// Download and add NotoSans font with full Cyrillic support
export const addNotoSansCyrillicFont = async (doc: any): Promise<boolean> => {
  const fontUrl = 'https://cdn.jsdelivr.net/npm/@fontsource/noto-sans@5.0.0/files/noto-sans-cyrillic-400-normal.woff2';
  
  try {
    const response = await fetch(fontUrl);
    if (!response.ok) throw new Error('Failed to fetch font');
    
    const arrayBuffer = await response.arrayBuffer();
    const uint8Array = new Uint8Array(arrayBuffer);
    let binary = '';
    for (let i = 0; i < uint8Array.byteLength; i++) {
      binary += String.fromCharCode(uint8Array[i]);
    }
    const base64 = btoa(binary);
    
    doc.addFileToVFS('NotoSans-Regular.ttf', base64);
    doc.addFont('NotoSans-Regular.ttf', 'NotoSans', 'normal');
    doc.setFont('NotoSans');
    return true;
  } catch (error) {
    console.error('Failed to load NotoSans font:', error);
    return false;
  }
};

// Fallback: Use PTSans from reliable CDN
export const addPTSansFont = async (doc: any): Promise<boolean> => {
  // PT Sans Regular with Cyrillic - reliable source
  const fontUrl = 'https://fonts.gstatic.com/s/ptsans/v17/jizaRExUiTo99u79D0KEwA.ttf';
  
  try {
    const response = await fetch(fontUrl);
    if (!response.ok) throw new Error('Failed to fetch font');
    
    const arrayBuffer = await response.arrayBuffer();
    const uint8Array = new Uint8Array(arrayBuffer);
    let binary = '';
    for (let i = 0; i < uint8Array.byteLength; i++) {
      binary += String.fromCharCode(uint8Array[i]);
    }
    const base64 = btoa(binary);
    
    doc.addFileToVFS('PTSans-Regular.ttf', base64);
    doc.addFont('PTSans-Regular.ttf', 'PTSans', 'normal');
    doc.setFont('PTSans');
    return true;
  } catch (error) {
    console.error('Failed to load PTSans font:', error);
    return false;
  }
};
